src/WebApps/PhoneBook.Web/Models/ErrorViewModel.cs
using System;

namespace PhoneBook.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebApps/PhoneBook.Web/Models/PersonContactDto.cs
using System;

namespace PhoneBook.Web.Models
{
    public class PersonContactDto
    {
        public Guid Id { get; set; }
        public Guid PersonId { get; set; }
        public int ContactTypeId { get; set; }
        public string Value { get; set; }
    }
}

src/WebApps/PhoneBook.Web/Models/PersonDto.cs
using System;

namespace PhoneBook.Web.Models
{
    public class PersonDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Company { get; set; }
    }
}

src/WebApps/PhoneBook.Web/Models/RequestModel.cs
using System;

namespace PhoneBook.Web.Models
{
    public class RequestModel
    {
        public Guid id { get; set; }
    }
}

src/WebApps/PhoneBook.Web/Models/ServiceSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneBook.Web.Models
{
    public class ServiceSettings
    {
        public string PersonApiUrl { get; set; }
        public string ReportApiUrl { get; set; }
    }
}

src/WebApps/PhoneBook.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhoneBook.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebApps/PhoneBook.Web/Controllers/KisiController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Models;
using PhoneBook.Web.Services.Abstract;
using System;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class KisiController : Controller
    {
        private readonly IPersonService _personService;

        public KisiController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetPersonList()
        {
            var result = await _personService.GetPersonList();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> GetPersonContacts([FromBody] RequestModel model)
        {
            var result = await _personService.GetPersonContactsByPersonId(model.id);

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> GetContactTypes()
        {
            var result = await _personService.GetContactTypes();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> SavePerson([FromBody] PersonDto model)
        {
            var result = await _personService.SavePerson(model);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> DeletePerson([FromBody] RequestModel model)
        {
            var result = await _personService.DeletePerson(model.id);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        
    }
}

src/WebApps/PhoneBook.Web/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Models;
using PhoneBook.Web.Services.Abstract;
using System;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonService _personService;

        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetPersonList()
        {
            var result = await _personService.GetPersonList();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> GetPersonContacts([FromBody] RequestModel model)
        {
            var result = await _personService.GetPersonContactsByPersonId(model.id);

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> GetContactTypes()
        {
            var result = await _personService.GetContactTypes();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> SavePerson([FromBody] PersonDto model)
        {
            var result = await _personService.SavePerson(model);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> DeletePerson([FromBody] RequestModel model)
        {
            var result = await _personService.DeletePerson(model.id);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> SaveContact([FromBody] PersonContactDto model)
        {
            var result = await _personService.SavePersonContact(model);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> DeletePersonContact([FromBody] RequestModel model)
        {
            var result = await _personService.DeletePersonContact(model.id);
            return new ContentResult() { Content = result, ContentType = "application/json" };
        }



    }
}

src/WebApps/PhoneBook.Web/Controllers/RaporController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class RaporController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/WebApps/PhoneBook.Web/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Web.Services.Abstract;
using System;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;

        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> GetReportList()
        {
            var result = await _reportService.GetList();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> SaveReport()
        {
            var result = await _reportService.SaveReport();

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }

        [HttpPost]
        public async Task<IActionResult> GetReportData(Guid id)
        {
            var result = await _reportService.GetReportData(id);

            return new ContentResult() { Content = result, ContentType = "application/json" };
        }
    }
}

src/WebApps/PhoneBook.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hoş Geldiniz</h1>
    
</div>

src/WebApps/PhoneBook.Web/Views/Kisi/Index.cshtml
@{
    ViewBag.Title = "Kişiler";
}

<h1 class="display-4">Kişiler</h1>
<hr />

<div id="app">
    <div class="row">
        <div class="col-12">
            <h4 class="">
                Kişi Listesi
            </h4>
        </div>

        <div class="col-4">

            <ul class="list-group">
                <li class="list-group-item list-group-item-action text-primary" v-on:click="addPerson()" style="cursor:pointer;">
                    <i class="fas fa-plus"></i> Kişi Ekle
                </li>
                <li class="list-group-item list-group-item-action" v-for="item in personList">
                    <div v-on:click="getPersonDetail(item)" style="cursor:pointer;">
                        <p class="mb-0"> {{item.name + ' ' + item.surname}} </p>
                        <small class="text-muted">{{item.company}}</small>
                    </div>

                    <button class="btn btn-light position-absolute btn-sm" style="right:10px; bottom:10px;" v-on:click="deletePersonConfirmation(item)">
                        <i class="far fa-trash-alt"></i>
                    </button>
                </li>
            </ul>
        </div>
        <div class="col-8">
            <h5 class="">
                Kişi Bilgileri
            </h5>
            <div class="card border">
                <div class="card-body">
                    <form v-on:submit="savePerson($event)" id="personForm">
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Adı</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="selectedPerson.name" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Soyadı</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="selectedPerson.surname" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Firma</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="selectedPerson.company">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <button class="btn btn-success float-right" type="submit">Kaydet</button>
                            </div>
                        </div>
                    </form>

                    <hr />
                    <h5 class="">
                        İletişim Bilgileri
                    </h5>

                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action text-primary" v-on:click="addContact()" style="cursor:pointer;" v-if="selectedPerson.id != undefined">
                            <i class="fas fa-plus"></i> İletişim Bilgisi Ekle
                        </li>

                        <li class="list-group-item list-group-item-action" v-for="item in selectedPersonContacts">
                            <div class="text-muted" v-on:click="selectPersonContact(item)" style="cursor:pointer;">
                                <p v-html="getContactTypeValue(item.contactTypeId)" class="mb-0  font-weight-bold"></p>
                                <span class="text-muted">{{item.value}}</span>
                            </div>

                            <button class="btn btn-light position-absolute btn-sm" style="right:10px; bottom:10px;" v-on:click="deleteContactConfirmation(item)">
                                <i class="far fa-trash-alt"></i>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Kişi Silme Onayı</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    "{{deletedPerson.name + ' ' + deletedPerson.surname}}" kişisini silmek için onaylayınız.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="button" class="btn btn-primary" v-on:click="deletePerson()">Onayla</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteContactModal" tabindex="-1" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">İletişim Bilgisi Silme Onayı</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Silmek için onaylayınız.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="button" class="btn btn-primary" v-on:click="deleteContact()">Onayla</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        const kisiApp = {
            data() {
                return {
                    personList: [],
                    selectedPerson: {},
                    contactTypes: {},
                    selectedPersonContacts: [],
                    deletedPerson: {},
                    deletedContact: {},

                }
            },

            methods: {

                getPersonList() {
                    axios.post("/Kisi/GetPersonList")
                        .then(res => {
                            this.personList = res.data;
                        });
                },

                getPersonDetail(kisi) {

                    let p = { id: kisi.id };
                    axios.post("/Kisi/GetPersonContacts", p)
                        .then(res => {

                            this.selectedPerson = Object.assign({}, kisi);
                            this.selectedPersonContacts = res.data;
                        });
                },

                getContactTypes() {

                    axios.post("/Kisi/GetContactTypes")
                        .then(res => {
                            this.contactTypes = res.data;
                        });
                },

                getContactTypeValue(id) {
                    return this.contactTypes.filter(a => a.id == id)[0].value;
                },

                addPerson() {
                    this.selectedPerson = {};
                    this.selectedPersonContacts = [];
                },

                savePerson(event) {
                    event.preventDefault();

                    axios.post("/Kisi/SavePerson", this.selectedPerson)
                        .then(res => {
                            if (res.data.error != undefined) {
                                toastr.error(res.data.error);
                                return false;
                            }

                            let tempArray = this.personList.filter(a => a.id != res.data.id);
                            tempArray.splice(0, 0, Object.assign({}, res.data));
                            this.personList = tempArray;

                            this.selectedPerson = res.data;
                            toastr.success("Kayıt Başarılı");
                        });
                },

                deletePerson() {
                    if (this.deletedPerson.id != undefined) {
                        let p = { id: this.deletedPerson.id };
                        axios.post("/Kisi/DeletePerson", p )
                            .then(res => {
                                if (res.data.error != undefined) {
                                    toastr.error(res.data.error);
                                    return false;
                                }

                                let tempArray = this.personList.filter(a => a.id != this.deletedPerson.id);
                                this.personList = tempArray;

                                this.deletedPerson = {};
                                this.selectedPerson = {};
                                toastr.success("İşlem Başarılı");
                                $('#deleteConfirmationModal').modal("hide");

                            });
                    }
                },

                deletePersonConfirmation(person) {
                    this.deletedPerson = person;
                    $('#deleteConfirmationModal').modal("show");
                },

                deleteContactConfirmation(contact) {
                    this.deletedContact = contact;
                    $('#deleteContactModal').modal("show");
                }
            },

            mounted: function () {
                this.getContactTypes();
                this.getPersonList();
            },

            computed: {
            }

        };

        const vmKisiApp = Vue.createApp(kisiApp).mount('#app');
    </script>
}

src/WebApps/PhoneBook.Web/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Raporlar";
}

<h1 class="display-4">Raporlar</h1>
<hr />

<div id="app">
    <div class="row">
        <div class="col-12">
            <h4 class="">
                Rapor Listesi
            </h4>
        </div>

        <div class="col-5">

            <ul class="list-group">
                <li class="list-group-item list-group-item-action text-primary" v-on:click="saveReport()" style="cursor:pointer;">
                    <i class="fas fa-plus"></i> Rapor Talebi Oluştur
                </li>
                <li class="list-group-item list-group-item-action" v-for="item in reportList" style="cursor:pointer;">
                    <div v-on:click="getReportData(item)" style="cursor:pointer;">
                        <p class="mb-0"> {{item.id + '.pdf ' }} </p>
                        <small class="text-muted">{{tarihFormatla(item.requestDate)}}</small>
                    </div>
                    <button class="btn btn-light position-absolute btn-sm" style="right:10px; bottom:10px;" v-if="item.status == 'Tamamlandı'">
                        {{item.status}}
                    </button>
                    <button class="btn btn-primary position-absolute btn-sm" style="right:10px; bottom:10px;" v-else>
                        {{item.status}}
                    </button>
                </li>
            </ul>
        </div>

        <div class="col-7">
            <h4 class="">
                Rapor İçeriği
            </h4>

            <div class="row">
                <div class="col-6">
                    <small class="text-muted font-weight-bold">Rapor Adı: </small> 
                    <div>{{selectedReport.id}}</div>
                </div>
                <div class="col-6">
                    <small class="text-muted font-weight-bold">Rapor Talep Tarihi : </small> 
                    <div>{{tarihFormatla(selectedReport.requestDate)}}</div>
                </div>
            </div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Konum</th>
                        <th>Rehbere Kayıtlı Kişi Sayısı</th>
                        <th>Rehbere Kayıtlı Telefon Numarası Sayısı</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in reportData">
                        <td>{{item.location}}</td>
                        <td>{{item.registeredPersonCount}}</td>
                        <td>{{item.registeredPhoneNoCount}}</td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>

</div>

@section Header{

    <script src="~/lib/signalr/signalr.min.js"></script>
    <script>
        $(document).ready(function () {
            const signalRConn = new signalR.HubConnectionBuilder()
                .withUrl("/reportHub").build();
            signalRConn.start();

            signalRConn.on("reportCreated", messege => {
                vmReportApp.reportCreated(messege);
            })
        })
    </script>
}

@section Scripts{
    <script>

        const reportApp = {
            data() {
                return {
                    reportList: [],
                    reportData: [],
                    selectedReport: {},
                }
            },

            methods: {

                getReportList() {
                    axios.post("/Report/GetReportList")
                        .then(res => {
                            this.reportList = res.data;
                        });
                },

                saveReport() {

                    let p = {};
                    axios.post("/Report/SaveReport", p)
                        .then(res => {
                            if (res.data.error != undefined) {
                                toastr.error(res.data.error);
                                return false;
                            }

                            let tempArray = this.reportList.filter(a => a.id != res.data.id);
                            tempArray.splice(0, 0, Object.assign({}, res.data));
                            this.reportList = tempArray;

                            toastr.success("Kayıt Başarılı");
                        });
                },

                tarihFormatla(tarih) {
                    if (tarih == undefined)
                        return "";

                    return new Date(tarih).toLocaleDateString()
                },

                reportCreated(id) {
                    var report = this.reportList.filter(a => a.id == id)[0];
                    report.status = "Tamamlandı";
                },

                getReportData(report) {

                    axios.post("/Report/GetReportData?id=" + report.id)
                        .then(res => {
                            if (res.data.error != undefined) {
                                toastr.error(res.data.error);
                                return false;
                            }

                            this.reportData = res.data;
                            this.selectedReport = report;

                            toastr.success("Rapor Yüklendi.");
                        });
                }

            },

            mounted: function () {
                this.getReportList();
            },

            computed: {
            }

        };

        const vmReportApp = Vue.createApp(reportApp).mount('#app');
    </script>
}

src/WebApps/PhoneBook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Telefon Rehberi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Header", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Telefon Rehberi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Kişiler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Raporlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Ömer Faruk Asyalıoğlu
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vuejs/vue.global.prod.js"></script>
    <script src="~/lib/axios/axios.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>